Register Integration
wolox-training/mr-net-core pull request #55
Opened 2019-08-26 18:38 UTC by Marcosnr97

### Summary
- Added an integration with an external api to register users

### Trello Card
https://trello.com/c/XDfFFYNI/15-register-integration

2019-08-26 19:16 UTC, BJordi requested changes

2019-08-26 19:16 UTC, BJordi commented on wolox-books/src/views/Register.vue
> +        button.main-button.text-xsmall(@click='Submit')
Methods name goes in lower camelcase.

2019-08-26 19:16 UTC, BJordi commented on wolox-books/src/views/Register.vue
>  import { required, helpers, minLength, email } from 'vuelidate/lib/validators'
Add an empty line to separate library imports from services imports.

2019-10-08 18:21 UTC, LauchaBo requested changes

2019-10-08 18:21 UTC, LauchaBo commented on wolox-books/src/views/Register.vue
>  const passwordRegex = helpers.regex('passwordRegex', /^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[a-zA-Z]).{8,}$/)
Move this regex to a 'validators' file inside a 'utils' folder

2019-10-08 18:21 UTC, LauchaBo commented on wolox-books/src/views/Register.vue
> +        })
Use 'min-width' inside 'input-box' instead of 'max-width' and 'width' if the element is smaller than what you need.

2019-10-08 18:21 UTC, LauchaBo commented on wolox-books/src/services/AuthService.js
> +export const Register = userDetails => api.post('/users', userDetails)
register should be written in lowerCamelCase

2019-10-08 18:21 UTC, LauchaBo commented on wolox-books/src/views/Register.vue
> +            email: this.email,
use a const to define all variables as 'this' and you can remove all the 'this.'.

e.g.:
const { email, password } = this
register({ user: { email, password } })

2019-10-08 18:21 UTC, LauchaBo commented on wolox-books/src/views/Register.vue
> +    submit () {
This should be an async function.

e.g.:
    async loginUser() {
      if (this.$v.$invalid) {
        this.showErrors = true
      } else {
        const { email, password } = this
        if (email && password) {
          this.showErrors = false
          await this.login({ email, password })
        }
      }
    }

2019-10-15 20:03 UTC, LauchaBo approved these changes

2019-10-16 15:18 UTC, merged