Vue Router
wolox-training/mr-net-core pull request #56
Opened 2019-08-26 19:15 UTC by Marcosnr97

### Summary
- Added routes for login and register 

### Trello Card
https://trello.com/c/arSquYyn/18-vue-router

2019-08-26 19:21 UTC, BJordi requested changes

2019-08-26 19:21 UTC, BJordi commented on wolox-books/src/router.js
>        name: 'register',
Add a const object called `routes` or something like that to have all the routes names. Then, you can export it and use it somewhere else, and if you have to change a name you'll do it in just one place.

2019-08-26 19:21 UTC, BJordi commented on wolox-books/src/router.js
> +      component: () => import('./views/Register.vue')
Add the chunk name:
`component: () => import(/* webpackChunkName: "register" */ './views/Register.vue')`

2019-08-26 19:21 UTC, BJordi commented on wolox-books/src/router.js
> +      component: () => import('./views/Login.vue')
Do the same here, use that `routes` for the name and add the chunk name.

2019-08-26 19:21 UTC, BJordi commented on wolox-books/src/router.js
> +      redirect: { name: 'login' }
Use `routes` here too.

2019-08-26 19:21 UTC, BJordi commented on wolox-books/src/views/Register.vue
> +      router-link.secondary-button.text-xsmall.white(to='`/login`')
Remove the grave accent, just type `to='/login'`

2019-09-03 05:10 UTC, BJordi requested changes

2019-09-03 05:10 UTC, BJordi commented on wolox-books/src/views/Register.vue
> +        button.main-button.text-xsmall(@click='Submit')
`Submit` -> `submit`

2019-09-03 05:10 UTC, BJordi commented on wolox-books/src/views/Register.vue
> +      router-link.secondary-button.text-xsmall.white(to='/login')
`:to='router.login'`

2019-10-15 20:18 UTC, LauchaBo requested changes

2019-10-15 20:18 UTC, LauchaBo commented on wolox-books/src/views/Register.vue
> +   router-link.secondary-button.text-xsmall.white(:to='router.login')
Change the destination to '/login'

2019-10-15 20:18 UTC, LauchaBo commented on wolox-books/src/views/Register.vue
> +  display: flex;
Create a class 'center' outside this view in 'src/scss/commons/display.scss' and use that class in the pug code. Don't forget to add the new scss file to 'application.scss'

2019-10-16 15:19 UTC, Marcosnr97 commented on wolox-books/src/views/Register.vue
> +   router-link.secondary-button.text-xsmall.white(:to='router.login')
Check this comment from @BJordi https://github.com/wolox-training/mr-net-core/pull/56#discussion_r320092558 . :thinking:

2019-10-16 20:57 UTC, LauchaBo commented on wolox-books/src/views/Register.vue
> +   router-link.secondary-button.text-xsmall.white(:to='router.login')
I talked to @BJordi and it should be written this way, as it is the one recommended in the vue docs:

`router-link(:to='{ name: routes.login}')`

Adapt 'name' in router.js to routes.login so it works with the new format

2019-11-04 17:55 UTC, BJordi approved these changes

2019-11-05 16:13 UTC, merged